######################################################################
# Automatically generated by qmake (3.0) Fri May 11 12:56:16 2018
######################################################################

QT       += core gui concurrent

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = yu
INCLUDEPATH += .
INCLUDEPATH += /usr/include
# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
